<a href="https://colab.research.google.com/github/ngcheeyuan/Learner-s-Repo-for-Tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# we're going into cover:
*introduction to tensors
*getting information from tensors
* manipulating tensors
*tensors & numpy
*tf.function
*Using GPUs with Tensor flows


Introduction to Tensors

In [ ]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the dimension of our vector
vector.ndim

1

In [ ]:
#create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
#check the dimension of our matrix
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix = tf.constant([[10.,7.,3.],
                              [3.,2.,0],
                              [8.2,9.,2.]],dtype =tf.float16) # specify the data type
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10. ,  7. ,  3. ],
       [ 3. ,  2. ,  0. ],
       [ 8.2,  9. ,  2. ]], dtype=float16)>

In [ ]:
# what's the number of dimensions of another matrix
another_matrix.ndim

2

In [ ]:
#Let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
#check the dimension of our matrix
tensor.ndim

3

What we've created so far:

* Scalar: a a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2- dimensional array of numbers 
* Tensor: an n-dimensional array of numbers where n  can be any positive integer.

### Creating tensors with tf.variable

In [ ]:
# Create the same tensor with tf.Variables as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor =tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#let's try to change one of the elements
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(7)

AttributeError: ignored

### Creating random tensor

Random tensors are tensors of some arbitrary size which contains random numbers

In [ ]:
# Create two random (but the same) tensor
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))

In [ ]:
random_1 

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

#Shuffle a tensor

In [ ]:
not_shuffled = tf.constant([[10,7],[2,5],[3,4]])
not_shuffled.ndim

2

In [ ]:
not_

NameError: ignored

https://www.tensorflow.org/api_docs/python/tf/random/set_seed

It looks like if we want our shuffled tensors to be in the same order , we've got to use the global level random seed as well as the operation level random seed

>Rule 4: If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
# shuffle our non-shuffled-tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.shuffle(not_shuffled, seed = 42)

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

In [ ]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed = 1) # operation level random seed

In [ ]:
tf.random.shuffle(not_shuffled, seed = 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed = 3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed = 4)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed =42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

### Other ways to create tensors

In [ ]:
tf.ones([10,7]) # create a tensors with all 1

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([10,7]) # create a tensor with all 0

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [ ]:
import numpy as np

numpy_A = np.arange(1,13, dtype = np.int32)

#X = tf.constant(some_matrix) # capital for matrix or tensor
#y = tf.constant(vector) #non-capital for vector
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A,shape = (2,3,2))
A,B

(<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],
 
        [[ 7,  8],
         [ 9, 10],
         [11, 12]]], dtype=int32)>)

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis/Dimension
* Size

In [ ]:
# create a rank 4 dimension

rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print('Datatype of every element:' , rank_4_tensor.dtype)
print('Num of dimensions:', rank_4_tensor.ndim)
print('Shape of tensor:', rank_4_tensor.shape)
print('Elements along the 0 axis:', rank_4_tensor.shape[0])
print('Eements along the first axis:', rank_4_tensor.shape[-1])
print('Total number of elements in our tensor:', tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Num of dimensions: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Eements along the first axis: 5
Total number of elements in our tensor: 120


### Indexing and expanding tensors

Tensors can be indexed just like python lists.

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
#create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor, rank_2_tensor.ndim, rank_2_tensor.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>, 2, TensorShape([2, 2]))

In [ ]:
# Get the last item of each of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extram dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

### Manipulating tensors(tensor operations)
Basic operations

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10 , tensor - 10 , tensor * 10 , tensor / 10 

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>)

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in function too.
tf.multiply(tensor,10) , tf.subtract(tensor,10) , tf.divide(tensor,10),tf.add(tensor,10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>)

# Matrix multiplication with tensors

In ML, matrix multiplcation is the most common tensor operations

1. The inner dimension must match
2. The resulting matrix has the shape of the inner dimension

In [ ]:
# Matrix multiplication in tensorflow

tf.linalg.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor2 = tf.constant([[3,5],[6,7],[1,8]])

In [ ]:
tf.linalg.matmul(tensor1,tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Matrix multiplication with python operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor1 = tf.constant([[1,2],[7,2],[3,3]])
tensor2 = tf.constant([[3,5],[6,7],[1,8]])

tf.linalg.matmul(tensor2,tf.transpose(tensor1))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 31, 24],
       [20, 56, 39],
       [17, 23, 27]], dtype=int32)>

In [ ]:
#let's change the shape of tensor 1
tf.linalg.matmul(tensor2,tf.reshape(tensor1,shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 21, 36],
       [20, 33, 63],
       [17, 26, 31]], dtype=int32)>

In [ ]:
tf.linalg.matmul(tensor2,tf.transpose(tensor1))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 31, 24],
       [20, 56, 39],
       [17, 23, 27]], dtype=int32)>

In [ ]:
tf.reshape(tensor1,shape = (2,3)) , tf.transpose(tensor1)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 7],
        [2, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 7, 3],
        [2, 2, 3]], dtype=int32)>)

** The dot product **
You can perform matrix multiplication using:
* 'tf.matmul()'
* 'tf.tensordot()'

In [ ]:
tensor1,tensor2 

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [7, 2],
        [3, 3]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [ ]:
tf.tensordot(tensor1,tf.transpose(tensor2),axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 20, 17],
       [31, 56, 23],
       [24, 39, 27]], dtype=int32)>

In [ ]:
tf.tensordot(tensor2,tf.transpose(tensor1),axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 31, 24],
       [20, 56, 39],
       [17, 23, 27]], dtype=int32)>

In [ ]:
tf.matmul(tensor1, tf.reshape(tensor2 , shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17,  7, 22],
       [35, 37, 58],
       [30, 18, 42]], dtype=int32)>

In [ ]:
X = tensor1
Y = tensor2

In [ ]:
print('Normal Y:')
print(Y, '\n')

print('Y reshaped to 2,3')
print(tf.reshape(Y,shape = (2,3)),'\n')

print('Y transposed')
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32) 

Y reshaped to 2,3
tf.Tensor(
[[3 5 6]
 [7 1 8]], shape=(2, 3), dtype=int32) 

Y transposed
tf.Tensor(
[[3 6 1]
 [5 7 8]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 20, 17],
       [31, 56, 23],
       [24, 39, 27]], dtype=int32)>

In [ ]:
tf.__version__

'2.7.0'

### Changing the datatypes

In [ ]:
# create a new tensor with default datatype(float32)
B = tf.constant([[1.7,7.4]])
B.dtype

tf.float32

In [ ]:
D = tf.cast(B , dtype =tf.float16)
D, D.dtype

(<tf.Tensor: shape=(1, 2), dtype=float16, numpy=array([[1.7, 7.4]], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int 32 to float 32
C = tf.constant([7,10])
E = tf.cast(D,dtype = tf.int16)
E,E.dtype

(<tf.Tensor: shape=(1, 2), dtype=int16, numpy=array([[1, 7]], dtype=int16)>,
 tf.int16)

### Aggregating tensors


In [ ]:
# Get the absolute values
D = tf.constant([-7,-10])
D

tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# min, max, mean

E = tf.constant(np.random.randint(0,100,size = 50))
tf.size(E) , tf.shape(E) , E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([50], dtype=int32)>,
 1)

In [ ]:
E = tf.cast(E, dtype = tf.float16)

In [ ]:
tf.reduce_min(E) , tf.reduce_max(E), tf.reduce_mean(E) , tf.reduce_sum(E) , tf.math.reduce_variance(E) ,  tf.math.reduce_std(E)

(<tf.Tensor: shape=(), dtype=float16, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=float16, numpy=99.0>,
 <tf.Tensor: shape=(), dtype=float16, numpy=48.88>,
 <tf.Tensor: shape=(), dtype=float16, numpy=2444.0>,
 <tf.Tensor: shape=(), dtype=float16, numpy=844.0>,
 <tf.Tensor: shape=(), dtype=float16, numpy=29.05>)

In [ ]:
some_list = [0,1,2,3,4]
tf.one_hot(some_list,depth = 5, on_value = 1 , off_value = 0 , dtype = tf.float32)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
### squaring, log and sqrt

H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H) , tf.sqrt(tf.cast(H,dtype = tf.float16)), tf.math.log(tf.cast(H,dtype = tf.float16))

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=float16, numpy=
 array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
       dtype=float16)>,
 <tf.Tensor: shape=(9,), dtype=float16, numpy=
 array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
        2.197 ], dtype=float16)>)

### Tensors & Numpy

In [ ]:
#Create a tensor directly from a NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(J)

array([ 3.,  7., 10.])

In [ ]:
J.numpy() , type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
#The default type of each are slightly different.

numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.10,])
numpy_J.dtype , tensor_J.dtype

(tf.float64, tf.float32)

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Jan 10 06:03:52 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P8    31W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note** : If you have access to a CUDA-enabled GPU, Tensorflow will auotomatically use it whenever possible